name: habits_timer
description: Simple habit-based time tracker with timers, stats & goals.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State management
  flutter_riverpod: ^2.5.1

  # Charts (utilisé plus tard)
  fl_chart: ^0.68.0

  # Dates / locales
  intl: ^0.19.0

  # Database (Drift + SQLite) — intégré plus tard
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  path: ^1.9.0

  # Notifications (plus tard)
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4

  # Utils
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  drift_dev: ^2.18.0

flutter:
  uses-material-design: true
